Add SamuraiHudWindow
jdsmith2816/delvui pull request #1
Opened 2021-08-23 14:37 UTC by abazilla

Had a go at adding Samurai to the list of HUDs! Please give me some feedback - it's both my first time in C# and contributing to open source :) 

gif: https://imgur.com/XN6bqJr

2021-08-23 20:12 UTC, jdsmith2816 requested changes
This mostly looks fine to me other than the few comments I left.  Great first PR!

One final note... Let's try to keep the commitlog relatively clean.  When you update the PR for needed changes go ahead and squash down to one commit with a message like

`feat: add samurai support with custom job gauges`

2021-08-23 20:12 UTC, jdsmith2816 commented on Interface/SamuraiHudWindow.cs
> +            // const int xPadding = 5;
Let's try to keep commented out code out of the repo;  everything is in source control so we can always bring it back if we need it.

2021-08-23 20:12 UTC, jdsmith2816 commented on Interface/SamuraiHudWindow.cs
> +            for (var i = 1; i < 4; i++) {
Why are you looping over this? I don't think we're gaining anything in clarity or brevity here. 

Personally I think we remove the loop and the `if i == #` checks and just have the duplicated cursorpos and border rect lines.

2021-08-23 20:12 UTC, jdsmith2816 commented on Interface/SamuraiHudWindow.cs
> +                        ImGui.ColorConvertFloat4ToU32(new Vector4(89 / 255f, 234 / 255f, 247 / 255f, 255f))
IMO we should just directly put the color here.   If you google `rgb to hex` you'll get a little widget with an RGB box on the bottom left that you can type `89 234 247` into and it'll show you the HEX value of `#59eaf7` 

Now that you know the hexcode you can replace this line of code with 0xAABBGGRR  AA is FF for 100% opacity so your color becomes.. 0xFFF7EA59

Repeat this process for the other three colors.

2021-08-25 09:51 UTC, abazilla commented
All done! :) thanks for the review.

2021-08-25 09:55 UTC, jdsmith2816 commented
Thanks abazilla!

2021-08-25 09:55 UTC, merged